# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:categories/:title/
#relative_permalinks: true

# Setup
title:               이기승의 끄적끄적..
tagline:             '개발 및 잡다한 포스팅'
description:         '&nbsp;잡기에 능한 개발자입니다. 개발 실력이 잡기보다 좋아야 할 텐데 걱정입니다.'
url:                 https://ntz4kiseung.github.io/
baseurl:             ''
imgbase:		'/public/image/'
docbase:		'/public/document/'
paginate:            6
gems:                [jekyll-paginate, gemoji, jemoji]
plugins:		[jekyll-paginate, gemoji, jemoji]
postroot:   'posts'
rootfolder:
   About Me : 
      subfolder : false
   Daily Thoughts : 
      subfolder : false
   Projects: 
      Sagyo Reboot:
         subfolder : false         
   Study :
      Http The Definitive Guide : 
         subfolder : false
   Googling :
      etc :
         subfolder : false
      java : 
         subfolder : false
      jekyll :
         subfolder : false
      linux :
         subfolder : false
      network :
         subfolder : false
      python : 
         subfolder : false


# About/contact
author:
  name:              Lee Kiseung
  url:               https://github.com/ntz4kiseung
  email:             ntz4kiseung@gmail.com

# Custom vars
version:             1.0.0
