# Setup
title:               Just a note
url:                 https://giseung-lee.github.io/
baseurl:             /public-notes
permalink:           pretty

# About/contact
author:
   name:              giseung.lee
   email:             goodexample.lee@gmail.com
