# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:categories/:title/
#relative_permalinks: true

# Setup
title:               이기승의 개발일지
tagline:             '문서화에 맛들리는 중...'
description:         '&nbsp;웹 백엔드의 기초를 닦고 있습니다. 시간이 흐르고 개발 툴의 트렌드가 바뀌어도 변하지 않는 요소들에 관심을 두고있습니다.'
url:                 https://ntz4kiseung.github.io/
baseurl:             ''
imgbase:		'/public/image/'
paginate:            5
gems:                [jekyll-paginate, gemoji, jemoji]
plugins:		[jekyll-paginate, gemoji, jemoji]
postroot:   'posts'
rootfolder:
   about : 
      subfolder : false
   projects: 
      twitch_chat_anaylsis: 
         subfolder : false
      sagyo_reboot:
         subfolder : false
      depth3:
         depth3-1:
             subfolder: false
         depth3-2:
             subfolder : false
   study_book :
      http_the_definitive_guide : 
         subfolder : false
      algorithm : 
         subfolder : false
   study_googling :
      etc :
         subfolder : false
      java : 
         subfolder : false
      jekyll :
         subfolder : false
      linux :
         subfolder : false
      network :
         subfolder : false
      python : 
         subfolder : false


# About/contact
author:
  name:              Lee Kiseung
  url:               https://github.com/ntz4kiseung
  email:             ntz4kiseung@gmail.com

# Custom vars
version:             1.0.0
