# Setup
title:               Just a note
url:                 https://localhost:4000/
baseurl:             ''
permalink:           pretty

# About/contact
author:
   name:              giseung.lee
   email:             goodexample.lee@gmail.com
