# Setup
title:               giseung.lee 개발 블로그
url:                 https://ntz4kiseung.github.io/
baseurl:             ''
permalink:           pretty

# About/contact
author:
   name:              giseung.lee
   url:               https://ntz4kiseung.github.io/
   email:             ntz4kiseung@gmail.com
