# Setup
title:               Just a note
url:                 https://giseung-lee.github.io/
baseurl:             ''
permalink:           pretty

# About/contact
author:
   name:              giseung.lee
   url:               https://giseung-lee.github.io/
   email:             goodexample.lee@gmail.com
