# Setup
title:               Just a note
url:                 http://localhost:4000/
baseurl:             ''
permalink:           pretty

# About/contact
author:
   name:              giseung.lee
   url:               http://localhost:4000/
   email:             goodexample.lee@gmail.com
